apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openfaas-ingress
  namespace: {{ .Values.global.coreNamespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/limit-connections: {{ .Values.ingress.maxConnections | quote }}
    nginx.ingress.kubernetes.io/limit-rpm: {{ .Values.ingress.requestsPerMinute | quote }}
    {{- if .Values.tls.enabled }}
    {{- if eq .Values.tls.issuerType "prod" }}
    cert-manager.io/issuer: letsencrypt-prod
      {{- else }}
    cert-manager.io/issuer: letsencrypt-staging
    {{- end }}
    {{- end }}
  labels:
    app: faas-netesd
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - {{ printf "*.%s" .Values.global.rootDomain | quote }}
    secretName: wildcard-{{ .Values.global.rootDomain }}-cert
  {{- end }}
  rules:
  - host: {{ printf "*.%s" .Values.global.rootDomain | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: edge-router
          servicePort: 8080
