apiVersion: v1
kind: Service
metadata:
  name: edge-router
  namespace: {{ .Values.global.coreNamespace }}
  labels:
    app: edge-router
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: edge-router
