apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: openfaas
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: openfaas
  labels:
    app: registry
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31115
  selector:
    app: registry
