provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  system-github-event:
    lang: go
    handler: ./github-event
    image: ghcr.io/${REPO:-openfaas}/ofc-github-event:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      write_debug: true
      read_debug: true
      validate_customers: true
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - customers
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  github-push:
    lang: go
    handler: ./github-push
    image: ghcr.io/${REPO:-openfaas}/ofc-github-push:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - customers
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m
  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: ghcr.io/${REPO:-openfaas}/ofc-git-tar:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - payload-secret
      - private-key
  # Uncomment this for GitLab
  #      - gitlab-api-token
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: ghcr.io/${REPO:-openfaas}/ofc-buildshiprun:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
      scaling_factor: 50
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
  #      - swarm-pull-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: ghcr.io/${REPO:-openfaas}/ofc-garbage-collect:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  github-status:
    lang: go
    handler: ./github-status
    image: ghcr.io/${REPO:-openfaas}/ofc-github-status:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      combine_output: false
      validate_hmac: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: ghcr.io/${REPO:-openfaas}/ofc-import-secrets:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: ghcr.io/${REPO:-openfaas}/ofc-pipeline-log:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  list-functions:
    lang: go
    handler: ./list-functions
    image: ghcr.io/${REPO:-openfaas}/ofc-list-functions:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: false
      read_debug: false
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  audit-event:
    lang: go
    handler: ./audit-event
    image: ghcr.io/${REPO:-openfaas}/ofc-audit-event:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - slack.yml
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  metrics:
    lang: go
    handler: ./metrics
    image: ghcr.io/${REPO:-openfaas}/ofc-system-metrics:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  function-logs:
    lang: go
    handler: ./function-logs
    image: ghcr.io/${REPO:-openfaas}/ofc-function-logs:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
    limits:
      memory: 128Mi
    requests:
      memory: 32Mi
      cpu: 50m

  echo:
    lang: go
    handler: ./echo
    image: ghcr.io/${REPO:-openfaas}/ofc-echo:${TAG:-dev}
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    limits:
      memory: 64Mi
    requests:
      memory: 32Mi
      cpu: 50m
