[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.25.9"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.3"

[prune]
  go-tests = true
  unused-packages = true
