{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.global.coreNamespace }}
  namespace: {{ .Values.global.coreNamespace }}
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: openfaas-system
    - namespaceSelector:
        matchLabels:
          role: {{ .Values.global.functionsNamespace }}
      podSelector:
        matchLabels:
          role: openfaas-system
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: nginx-ingress
{{- end }}