kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-sealed-secrets
  namespace: {{ .Values.global.functionsNamespace }}
subjects:
- kind: ServiceAccount
  name: sealedsecrets-importer-rw
  namespace: {{ .Values.global.functionsNamespace }}
roleRef:
  kind: ClusterRole
  name: sealedsecrets-importer
  apiGroup: rbac.authorization.k8s.io
