[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alexellis/hmac"
  version = "1.2.0"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.3"

