[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.14.2"

[prune]
  go-tests = true
  unused-packages = true
