name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  test-chart:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Tests
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash && make test-chart
  build-stack:
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack-file: [
        stack.yml,
        aws.yml,
        gitlab.yml
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Build
        run: STACKFILE=${{ matrix.stack-file }} sh ./contrib/ci.sh

  build-gateway:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Make dist
        run: cd dashboard && make build-dist && cd ..
      - name: Run Build
        run: STACKFILE=dashboard/stack.yml sh ./contrib/ci.sh

  # Test building the non-cli Containers
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
        svc: [
          edge-auth,
          edge-router,
          of-builder
        ]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::dev
      - name: Get Repo
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.svc }}
          file: ./${{ matrix.svc }}/Dockerfile
          outputs: "type=image,push=false"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:${{ github.sha }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:latest
