name: publish

on:
  push:
    tags:
      - '*'


jobs:
  publish-stack:
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack-file: [
          stack.yml,
          aws.yml,
          gitlab.yml
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.event.repository.owner.login }} | tr '[:upper:]' '[:lower:]')
      - name: Deploy Stacks
        run: STACKFILE=${{ matrix.stack-file }} TAG=${{ steps.get_tag.outputs.TAG }} REPO=${{ steps.get_repo_owner.outputs.repo_owner }} sh ./contrib/publish.sh

  publish-dashboard:
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack-file: [
          dashboard/stack.yml,
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.event.repository.owner.login }} | tr '[:upper:]' '[:lower:]')
      - name: Build Dist
        run: cd dashboard && make build-dist && cd ..
      - name: Deploy Stacks
        run: STACKFILE=${{ matrix.stack-file }} TAG=${{ steps.get_tag.outputs.TAG }} REPO=${{ steps.get_repo_owner.outputs.repo_owner }} sh ./contrib/publish.sh

  publish-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
        svc: [
          edge-auth,
          edge-router,
          of-builder
        ]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.svc }}
          file: ./${{ matrix.svc }}/Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:${{ github.sha }}
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/ofc-${{ matrix.svc }}:latest
